import type { Metadata } from "next";
import { cookies } from "next/headers";
import { Geist, Geist_Mono } from "next/font/google";
import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";
import {
  LOCALE_COOKIE,
  getLocaleDirection,
  isAppLocale,
  type AppLocale
} from "@/constants/locale";
import { Toaster } from "sonner";
import { TooltipProvider } from "@/components/ui/tooltip";
import { DirectionProvider } from "@/components/app/direction-provider";
import { ThemeProvider } from "@/components/app/theme-provider";
import { LoadingIndicator } from "@/components/ui/loading-indicator";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"]
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"]
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default async function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  const messages = await getMessages();
  const cookieStore = await cookies();
  const raw = cookieStore.get(LOCALE_COOKIE)?.value ?? "en";
  const htmlLang: AppLocale = isAppLocale(raw) ? raw : "en";
  const htmlDir = getLocaleDirection(htmlLang);

  return (
    <html lang={htmlLang} dir={htmlDir}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NextIntlClientProvider messages={messages}>
          <DirectionProvider dir={htmlDir}>
            <ThemeProvider>
              <TooltipProvider>
                {children}
                <Toaster position={htmlDir === "rtl" ? "top-left" : "top-right"} />
                <LoadingIndicator variant='overlay' loadingKey='axios' />
              </TooltipProvider>
            </ThemeProvider>
          </DirectionProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
